# -*- coding: utf-8 -*-
import http.server
import socketserver
import logging



class MyHttpRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # logging.info(self.path)
        # self.path = 'index.html'
        # return http.server.SimpleHTTPRequestHandler.do_GET(self)

        # Sending an '200 OK' response
        self.send_response(200)

        # Setting the header
        self.send_header('Content-type', 'text/html')

        # Whenever using 'send_header', you also have to call 'end_headers'
        self.end_headers()

        # Some custom HTML code, possibly generated by another function
        html = f"<html><head></head><body><h1>Hello Welt!</h1></body></html>"

        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))

        return


PORT = 8080
my_server = socketserver.TCPServer(('', PORT), MyHttpRequestHandler)

# Star the server
my_server.serve_forever()
